[tool.poetry]
name = "dara_data_interactivity"
authors = []
description = ""
version = "1.0.0"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8.0, <3.12.0"
dara-core = "<2.0.0"
dara-components = "<2.0.0"
