[tool.poetry]
name = "dara_interactivity"
authors = []
description = ""
version = "1.0.0"

[tool.poetry.dependencies]
python = ">=3.8.0, <3.12.0"
dara-core = "<2.0.0"
dara-components = "<2.0.0"
scikit-learn = "1.2.2"
